project:
  type: website
  output-dir: docs
  
website:
  title: "Lectures and Projects"
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: false
  favicon: Images/DSDE-Social-Media-Profile.png
  search: false
  repo-url: https://github.com/ysph-dsde/2025-bdsy
  issue-url: https://github.com/ysph-dsde/2025-bdsy/issues
  repo-actions: [source, issue]
  navbar:
    left:
      - text: "Lecture Materials"
        menu:
          - text: "Week 1"
            href: Pages/Week1.qmd
          - text: "Week 2"
            href: Pages/Week2.qmd
          - text: "Week 3"
            href: Pages/Week3.qmd
          - text: "Week 4"
            href: Pages/Week4.qmd
          - text: "Week 5"
            href: Pages/Week5.qmd
          - text: "Week 6"
            href: Pages/Week6.qmd
      - text: "Afternoon Groups"
        menu:
          - text: "Public Health Modeling"
            href: https://ysph-dsde.github.io/bdsy-phm/
            target: _blank
    right:
      - text: 2025 BDSY
        href: https://ysph-dsde.github.io/bdsy-phm/
        target: _blank
  page-footer:
    background: light 
    left: |
      This site was built on a ysph-dsde.github.io page.
      <br>
      It was rendered using Quarto (v 1.6.3) and theme [flatly](https://github.com/thomaspark/bootswatch).
    center:
      - text: Course Canvas
        href: https://canvas.yale.edu/login
        target: _blank
      - icon: envelope 
        href: mailto:bdsy.ysph@yale.edu
      - icon: globe
        href: https://ysph.yale.edu/
        target: _blank
      - icon: people-fill
        href: https://ysph.yale.edu/public-health-research-and-practice/research-centers-and-initiatives/public-health-data-science-and-data-equity/
        target: _blank
    right: 
      - text: |
          Office Hours 12:30 PM - 1:30 PM 
          <br>
          60 College St., Room 206 or Zoom upon request
          <br>
          Walk-In: Tuesday or Wednesday
          <br>
          <a href="https://outlook.office.com/book/BigDataSummerImmersionatYaleBDSYOfficeHours@yale.edu/?ismsaljsauthenabled">Book Appointment</a>: Monday or Thursday

format:
  html:
    theme: 
      - flatly
      - _styles/custom.scss
    toc: true
    from: markdown+autolink_bare_uris
    html-math-method: katex
    
highlight-style: tango